### ISSUE TITLE
Bibliography titles are not divided

### ISSUE THREAD

**Issue by Alek96** [ArturB/WUT-Thesis#2]
If a title is too long in misc type, the title won't be divided.
This bug was observed when using the Overleaf platform with PdfLaTeX, LuaLaTeX and XeLaTeX.

example:
```latex
@misc{vcs_introduction_2,  
  author        = "David A. Wheeler",  
  title         = "Comments on Open Source Software / Free Software (OSS/FS) Software Configuration Management (SCM) / Revision-Control Systems",  
  year          = "2004",  
  note          = "Dostęp zdalny (07.09.2019): \url{http://www.surfline.com/surf-news/maldives-surf-access-controversy-update\_75296/}"  
}  
```
result:
![image](https://user-images.githubusercontent.com/19309791/64389142-ad45df80-d041-11e9-9bc2-df0ced2146a3.png)

My solution:
Change title style:
```latex
\DeclareFieldFormat
  [unpublished,misc]{title}{
    \textit{#1\isdot}
}
```
![image](https://user-images.githubusercontent.com/19309791/64389245-21808300-d042-11e9-875d-b24dab755bfd.png)

**Comment by ArturB** [comment]
Poproszę o informacje nt. wersji platformy (Windows/Linux), środowiska (miktex/texlive) oraz kompilatora, ponieważ u siebie nie mogę zreplikować tego błędu, ani na Windowsie, ani na Linuxie.

**Comment by Alek96** [comment]
Poprawiłem opis.
