### ISSUE TITLE
Zmień link do źródeł w poradniku dyplomanta

### ISSUE THREAD

**Issue by marcullo** [ArturB/WUT-Thesis#22]
W najnowszym releasie pliki projektu są w formacie `*.tar.gz` tymczasem [poradnik dyplomanta](http://www.ii.pw.edu.pl/ii_pol/Instytut-Informatyki/Nauczanie/Poradnik-dyplomanta/Przygotowanie-pracy-dyplomowej) odsyła do `*.zip`. Można poprosić o podmiankę:

```
https://github.com/ArturB/WUT-Thesis/releases/download/latest/WUT-Thesis.zip
```

na

```
https://github.com/ArturB/WUT-Thesis/releases
```

Dzięki za szablon!

**Comment by ArturB** [comment]
Słuszna uwaga, podmiana linku w poradniku dyplomanta to skomplikowana procedura :D ale poprawiłem typ archiwum w release.

**Comment by mrfifiak** [comment]
W instrukcji też jest niedziałający link (58. linia w README.md).
https://github.com/ArturB/WUT-Thesis/releases/download/latest/WUT-Thesis.zip pokazuje Not Found

**Comment by ArturB** [comment]
@mrfifiak poprawione
