### ISSUE TITLE
Popraw format tytułu w bibliografii

### ISSUE THREAD

**Issue by marcullo** [ArturB/WUT-Thesis#25]
Po kompilacji (TexStudio), jest problem ze znakami zapytania w literaturze:

```
P. Woźniak, ?Programowanie kwadratowe w usuwaniu efektu rozmycia ruchu w
fotografii cyfrowej?, prac. mag., Wydział Elektroniki i Technik Informacyjnych, Poli-
technika Warszawska, 2018
```

Dodanie tych zmian go obchodzi:

```diff
diff --git a/eiti/eiti-thesis.cls b/eiti/eiti-thesis.cls
index 0bb478f..c30096b 100644
--- a/eiti/eiti-thesis.cls
+++ b/eiti/eiti-thesis.cls
@@ -139,6 +139,13 @@
 % Load csquotes after inputenc
 %--------------------------------------
 \RequirePackage{csquotes}
+\DeclareQuoteStyle[quotes]{polish}
+{\quotedblbase}
+{\textquotedblright}
+[0.05em]
+{\quotesinglbase}
+{\fixligatures\textquoteright}
+\DeclareQuoteAlias[quotes]{polish}{polish}
 
 %--------------------------------
 % Define hyperref colors

```

Oprócz tego, czy wpisy typu `@misc` powinny być dla odmiany w kursywie?

A. M. Brodzki, _Implementation of own steganography protocol DCP-19, loosely based
on HICCUPS_, Dostęp zdalny...

**Comment by ArturB** [comment]
Na mojej maszynie brak takiego problemu xd
![obraz](https://user-images.githubusercontent.com/11396977/72254333-fca9a700-3603-11ea-9708-ad3a31012908.png)
Ale zwróciłem uwagę, że instrukcja w README dot. TexStudio jest niekompletna: aby szablon działał stabilnie w tym środowisku, należy wejść w Opcje -> Konfiguruj TexStudio -> Zbuduj i wybrać kompilator domyslny **tatexmk** oraz domyślne narzędzie bibliografii **biber**. 
Zaraz dopiszę to do README. 
![obraz](https://user-images.githubusercontent.com/11396977/72254412-45616000-3604-11ea-9bc1-63306477eab5.png)

**Comment by marcullo** [comment]
Ach nie zauważyłem odpowiedzi. Daj znać czy edytować PR czy sam dołączysz ew. zmiany z niego.
