### ISSUE TITLE
Wielostronicowy spis treści ma "0. Spis treści" w rogu

### ISSUE THREAD

**Issue by kekore** [ArturB/WUT-Thesis#26]
Wielostronicowy spis treści ma "0. Spis treści" w rogu.
Czy da się to w jakiś sposób wyłączyć?

**Comment by marcullo** [comment]
**eiti/eiti-thesis.cls**

```diff
@@ -197,11 +197,14 @@
 \renewcommand{\sectionmark}[1]{
     \markboth{#1}{#1}
 }
+\newcommand{\fancyheadsec}{
+    \ifnum\value{section}=0 {} \else {\thesection.} \fi
+}
 
 \fancyhead{}
 \fancyheadoffset{0cm} 
-\fancyhead[RO]{\nouppercase{\thesection.\hspace{8pt}\leftmark}}
-\fancyhead[LE]{\nouppercase{\thesection.\hspace{8pt}\leftmark}}
+\fancyhead[RO]{\nouppercase{\fancyheadsec\hspace{8pt}\leftmark}}
+\fancyhead[LE]{\nouppercase{\fancyheadsec\hspace{8pt}\leftmark}}
 \fancyfoot{}
 \fancyfoot[LE,RO]{\thepage}

```

skutkuje tym:

![image](https://user-images.githubusercontent.com/22369250/72251237-c49f6580-35fd-11ea-9dcc-6d3a764f0b91.png)

![image](https://user-images.githubusercontent.com/22369250/72251246-ca954680-35fd-11ea-9c82-c3622a09b5df.png)

Po wrzuceniu `hspace` do `fancyheadsec` i uzależnieniu od numeru sekcji będziesz w stanie wyrównać te teksty nagłówków w poziomie.

**Comment by marcullo** [comment]
Zakładają że bibliografia albo inne spisy bez numeru zajmą więcej niż stronę, ich numery chyba też trzeba będzie dołączyć. Jeśli ktoś ma pomysł jak zawrzeć wszystkie sekcji bez numerów w jednym wyrażeniu warunkowym. chętnie o tym usłyszę.

**Comment by ArturB** [comment]
@marcullo Lepiej chyba jest nadpisać domyślny styl, a następnie przełączać sobie styl strony w dowolnym miejscu, wedle uznania:
eiti-thesis.cls:

![obraz](https://user-images.githubusercontent.com/11396977/72263007-54eaa400-3618-11ea-8910-1b0ebedc14a4.png)

main.tex:

![obraz](https://user-images.githubusercontent.com/11396977/72263056-6c299180-3618-11ea-990e-46320bd44967.png)

Mamy zatem dwa style: *\pagestyle{plain}* bez nagłówka oraz *\pagestyle{headings}* z nagłówkami. Styl *plain* ustawiłem dla spisu treści oraz spisów na końcu, a styl *headings* - w pozostałych miejscach.

**Comment by ArturB** [comment]
@kekore naprawione w wersji 2.1.0, można ją pobrać z [Releases](https://github.com/ArturB/WUT-Thesis/releases). 
Aby zaktualizować dokument z poprzedniej wersji, wystarczy podmieć plik eiti-thesis.cls oraz main.tex.
