### ISSUE TITLE
Popraw rozmiar tekstu w elementach spisów

### ISSUE THREAD

**Issue by marcullo** [ArturB/WUT-Thesis#32]
Po dodaniu linijki z opcją `\small`

```diff
diff --git a/eiti/eiti-thesis.cls b/eiti/eiti-thesis.cls
index 0c659a1..351b4c7 100644
--- a/eiti/eiti-thesis.cls
+++ b/eiti/eiti-thesis.cls
@@ -485,6 +485,7 @@
     % \refstepcounter{section}
     \tocless\section{\hspace*{1.5ex} #1}
     \addcontentsline{app}{subsection}{\hspace*{-2.5ex}\arabic{section}.\hspace*{0.5ex} #1}
+    \addcontentsline{app}{subsection}{\small{\hspace*{-2.5ex}\arabic{section}.\hspace*{0.5ex} #1}}
 }
 
 \newcommand\listofappendices{%
```

dostajemy:

![image](https://user-images.githubusercontent.com/22369250/72686678-80c5c800-3af7-11ea-812e-fccbcbb2b07d.png)

i widać że dolny element spisu załączników ma taki sam rozmiar (chyba xD) jak element spisu tabel, co zapewne jest pożądane.

Przy spisie listingów (`\lstlistoflistings`) występuje ta sama sytuacja.

**Comment by ArturB** [comment]
Słuszna uwaga, poprawiłem rozmiar czcionki w spisie załączników oraz w spisie symboli i załączników (przy okazji zwróciłem uwage, że tam również brakowało \small). 
Nową wersję wrzuciłem na repo, a do [Releases](https://github.com/ArturB/WUT-Thesis/releases) archiwum z numerem 2.1.1. 
Dziękuję i zamykam.
