### ISSUE TITLE
Jak zmienić wszystkie czcionki?

### ISSUE THREAD

**Issue by kekore** [ArturB/WUT-Thesis#33]
W jaki sposób można zmienić wszystkie czcionki? Ponoć w II wymagają wszędzie Times New Roman, nawet na stronie tytułowej.

**Comment by przestaw** [comment]
Czcinka szablonu spełnia wymogi:
http://www.ii.pw.edu.pl/index.php/ii_pol/Instytut-Informatyki/Nauczanie/Poradnik-dyplomanta/Przygotowanie-pracy-dyplomowej
polecam zobaczyć koniec strony

**Comment by ArturB** [comment]
> W jaki sposób można zmienić wszystkie czcionki? 

Nie zmieniać, czcionka to akurat jeden z tych elementów szablonu, który omawiasz z Wydziałem najwcześniej i ta jest okej. 

Zamykam.
