### ISSUE TITLE
Figures in appendix brake the list of figures

### ISSUE THREAD

**Issue by cmanszew** [ArturB/WUT-Thesis#36]
Figures inserted in the appendix, appear in the LoF. Additionally the caption of the figure and the name of it, overlay. Using the following, doesn't help:
- \caption*
- \captionsetup{list=no}
- \addtocontents{lof}{\protect\setcounter{tocdepth}{0}}.
The last command actually fixes the problem, but it also deletes the content of list of tables and list of appendecies.

**Comment by ArturB** [comment]
OK, please give a screenshot.

**Comment by cmanszew** [comment]
Here is a screenshot, without using any of the above mentioned commands. My goal is to skip the figures in the LoF entirely. Unfortunately none of the options listed above doesn't work. The caption package documentation suggests using '\caption[]{<caption_text>}' which unfortunately doesn't either. It just makes the caption text disappear from the LoF, but 'Załącznik 2.' is still there.  

![Screenshot from 2020-02-02 00-40-42](https://user-images.githubusercontent.com/26208674/73600736-d1580f00-4554-11ea-81df-3a282711ff1d.png)

**Comment by pwozniak** [comment]
Hey,

thank you for the issue.

I have found the solution.
One has to put before first appendix:
```
\captionsetup[figure]{list = no}
```

Actually, one can do the same with tables:
```
\captionsetup[table]{list = no}
```

Source: [https://latex.org/forum/viewtopic.php?t=1316](https://latex.org/forum/viewtopic.php?t=1316)

I will close the issue and make the pull request ASAP.

**Comment by pwozniak** [comment]
@cmanszew, do you use TeXlive or MikTeX or Overleaf version?

I discovered that caption.sty on Overleaf doesn't have that functionality.

**Comment by cmanszew** [comment]
I use the Overleaf template, and as I already mentioned above, the '\captionsetup' command doesn't work, even with '[table]' option.

**Comment by pwozniak** [comment]
@cmanszew
Understood.

Frankly, there is nothing we can do. Overleaf still uses TexLive 2018, although they promised the update in late 2019. It looks like they use very old ```caption.sty```.

For the newest TeXlive 2019 and MikTeX the aforementioned solution works properly on TeXstudio.

# Solution for now
1. Create empty "latexmkrc" file.
2. Create folder "texfiles".
3. Insert into "latexmkrc" file that line:
```
$ENV{'TEXINPUTS'}='./texfiles//:' . $ENV{'TEXINPUTS'};
```
4. Download (newest caption library files)[https://www.ctan.org/tex-archive/macros/latex/contrib/caption] and put them into "texfiles" folder on Overleaf server.
5. Recompile.

(Source)[https://tex.stackexchange.com/questions/50697/how-can-i-keep-a-clean-document-folder-with-custom-cls-sty-bst-files-in-a-s/50847#50847]

Probably you have already found it out, but, unfortunately, it is the only solution right now.
But will try to find out the better one.

Hope it will help.

**Comment by pwozniak** [comment]
I'm closing the issue.

# Final solution
1. Add those line before first ```\appendix``` reference:
  ```
  \captionsetup[figure]{list = no} 
  \captionsetup[table]{list = no} 
  ```
2. Clone your project in Overleaf to upgrade to TeXLive 2019.
