### ISSUE TITLE
Package caption Warning: \label without proper reference

### ISSUE THREAD

**Issue by lidalida** [ArturB/WUT-Thesis#38]
W przykładowym pliku tex/1-wstep.tex obrazki są wstawiane w nie do końca dobry sposób, skutkujący warningiem z package caption, kiedy próbujemy się do nich odnieść przez \ref i wyświetlaniem w PDFie "??" zamiast właściwego numeru obrazka.
W kodzie wygląda to tak:
```
\begin{figure}[!h]
	\label{fig:nowe-logo-pw}
	\centering \includegraphics[width=0.5\linewidth]{logopw2.png}
	\caption{Współczesne logo Politechniki Warszawskiej}
\end{figure}

hjsjkdfgvhkfj \ref{fig:nowe-logo-pw} gdthdhtd
```
A w PDFie:
![Zrzut ekranu z 2020-03-26 19-05-47](https://user-images.githubusercontent.com/15252720/77680879-d9e92680-6f94-11ea-802d-ef035de71bb6.png)

Btw kliknięcie w te znaki zapytania skutkuje przeniesieniem do dobrego obrazka, tylko numerowanie jest zepsute. 
Ten sam problem jest z numerowaniem tabel wszystkiego, co ma \label i \caption.

Rozwiązanie jest takie, że najpierw trzeba podawać w kodzie \caption dla obrazka/tabeli, a dopiero później \label, wyjaśnienie można znaleźć np. tu https://tex.stackexchange.com/a/32326.

Nie ma żadnych referencji w tych przykładowych plikach, więc wygląda, jakby działało, ale taka poprawka mogłaby oszczędzić w przyszłości 5min komuś kopiującemu rzeczy z przykładów.
Mogę zrobić PRa z poprawkami, ale zaczekam na jakieś potwierdzenie, że mam rację.

**Comment by ArturB** [comment]
Zgadza się, zmieniłem zatem kolejność znaczników w przykładach oraz dopisałem odpowiednie komentarze. 
Dzięki za uwagę.
