### ISSUE TITLE
Połączenie projektów

### ISSUE THREAD

**Issue by mjbogusz** [ArturB/WUT-Thesis#39]
Nie jest to typowy issue, ale nie widzę sensu robienia 10 pomniejszych, wyjaśnienie poniżej ;)

Słowem wstępu: circa 2 lata temu [popełniłem taką templatkę](https://gitlab.com/mjbogusz/pweiti_thesis). Teraz (w związku z robieniem mgr-ki) ją oczyściłem, dodałem komentarze i wrzuciłem publicznie. I zaraz po tym otrzymałem linka do tego repo...

Jako, że Wasz projekt jest dużo mniej "surowy" oraz że przeszedł już *trudny proces akceptacji* w dziekanacie dydaktycznym II, myślę, że zamiast tworzyć konkurencję byłoby sensownym wnieść do tego projektu rzeczy, które udało mi się rozgryźć w inny sposób, niż Wam. Zwłaszcza, że wiem, że z wcześniejszych wersji mojego korzystało sporo osób w IA i bezproblemowo przechodziło to przez dziekanat dydaktyczny tegoż instytutu.

Potencjalne usprawnienia do "przeportowania":
* nagłówek i rodzaj pracy w wersjach wektorowych (udało mi się zdobyć odpowiednią czcionkę oraz logo PW w SVG i w Inkscape'ie wygenerować PDFy)
* marginesy (nie wiem, skąd te wartości u Was - rozporządzenie Rektora nr 57/2016 określa nieco inne) i ustawienia nowych stron
* układ strony tytułowej (`\hfill \break`? bez przesady, to nie Word (; ), w tym np opcjonalność nazwy specjalizacji, numer pracy w ewidencji etc
* numeracja stron - alfabetyczna do oświadczenia o autorstwie, numeryczna dalej
* streszczenie/abstrakt w makro, opcjonalnie na jednej stronie - co instytut to inne zalecenie, w IA obie wersje (polska/angielska) mają być na 1 stronie, II AFAIK wymaga na osobnych
* jakieś tam inne drobne poprawki typograficzne i/lub używalnościowe

Ten issue wrzucam jako propozycję dyskusji, co z w/w uważacie za sensowne i jak z tym dalej działać.

PS. "Copyleft" w `readme` nieco kłóci się z GPLv3 w `LICENSE` ;)

**Comment by ArturB** [comment]
Hej, moje wstępne odczucia są takie:
 - nagłówek w wersji wektorowej miód, postaramy się wdrożyć jak tylko znajdziemy trochę czasu :)
 - marginesy i układ strony: przeanalizujemy problem w najbliższym czasie;
 - numeracja: skąd pomysł, żeby do oświadczenia o autorstwie numeracja była alfabetyczna? mam podejrzenia graniczące z pewnością, że przedstawienie takiego czegoś u p. Wiesi w dziekanacie II skończyłoby się grubszą awanturą;
 - wspólna wersja dla wszystkich Instytutów miała być ustalona w bieżącym semestrze, no ale wszystko trochę się poprzesuwało z uwagi na epidemię;
 - licencje: Richard Stallman, jak i sama Free Software Foundation ma na ten temat inne zdanie; nie wdając się tutaj w szczegółowe rozważania nt. filozofii różnych otwartych licencji, pozwolę sobie tylko podkreślić, że Copyleft nie jest tożsame z pozostawaniem utworu w domenie publicznej (Public Domain). Nie należy tych pojęć używać zamiennie. Więcej szczegółow tu: [https://www.gnu.org/licenses/copyleft.en.html](https://www.gnu.org/licenses/copyleft.en.html). 
Dzięki za wykonaną przez Ciebie pracę, zajmę się tym więcej jak znajdę trochę czasu w najbliższej przyszłości 👍

**Comment by pwozniak** [comment]
@mjbogusz Jeśli chodzi o marginesy, to masz rację, aczkolwiek przypominam, że podane wartości marginesów w rozporządzeniu są jedynie **zalecane** przez byłego rektora PW. To samo dotyczy interlinii i wcięć w akapitach.

**Comment by ArturB** [comment]
Od otwarcia wątku minął ponad rok, zatem pozwolę sobie podsumować aktualny status podniesionych tu kwestii:
 - nagłówki wektorowe - istnieje już PR do tego, w niedługim czasie powinien być zmergowany;
 - marginesy - zostały już poprawione;
 - numeracja - tak jak pisałem powyżej, moim zdaniem nie ma potrzeby jej zmiany;
 - streszczenie na jednej stronie - jedynie bardzo krótkie streszczenia mogłyby zmieścić się na jednej stronie, z racji, że streszczenia na osobnych stronach są prostym i uniwersalnym rozwiązaniem i nikt jak do tej pory nie zgłaszał potrzeby zmian, to i ja nie widzę potrzeby kombinowania przy nich; 
 - strona tytułowa - szczegółowe, nietypowe modyfikacje (np. brak nazwy specjalizacji) każdy może wprowadzić samodzielnie. Nie sądzę, by była potrzebna zmiana zasadniczego szablonu. 

Jak widać, wątek z upływem czasu w zasadzie się zdezaktualizował, a niezbędne zmiany zostały już wprowadzone. Mając to na uwadze, zamykam.
