### ISSUE TITLE
Nieprawidłowe odnośniki do załączników

### ISSUE THREAD

**Issue by Juliette17** [ArturB/WUT-Thesis#40]
Kiedy do załącznika nr 1 nazwanego przy pomocy \label{appendix_name} chcę odnieść się przez komendę \ref{appendix_name}, to zamiast 1 wstawia inny numer: liczbę wszystkich rozdziałów przed załącznikami + 1, czyli w moim przypadku 7. Numer załącznika w spisie załączników i w samym tytule załącznika są prawidłowe. Chodzi tylko o odnośniki poprzez nazwę.

**Comment by ArturB** [comment]
Hmm, spis załączników jest w stanie nieco demonstracyjnym, i jak dotąd nie był projektowany pod kątem odwoływania się do nich za pomocą \ref; mnie zaskakuje, że LaTeX w ogóle wstawia tam jakąkolwiek liczbę :P 
Ja ze swej strony nie będę mógł tego poprawić przed 25 sierpnia, bo jest sporo innych zajęć, i do tego czasu trzeba chyba zastosować workaround i do załączników odwoływać się ręcznie (bez \ref). Chyba, że @pwozniak  jest w stanie coś tutaj napisać.

**Comment by adeele** [comment]
@Juliette17 miałam ten sam problem i denerwował mnie na tyle, że znalazłam rozwiązanie które działa u mnie. Jeśli u Ciebie jeszcze aktualne, byłoby świetnie gdybyś mogła przetestować to również na swoim przykładzie i podzielić się ze mną informacją zwrotną.
@ArturB powiem zupełnie szczerze, że nie znam się na tworzeniu szablonów do LaTeXa, więc zmiany robiłam właściwie po omacku. Nie wiem też za bardzo czy jest jakiś dobry sposób przetestowania mojego rozwiązania. Jednak stwierdziłam, że może Wam też się przyda ten kawałek kodu, dlatego utworzyłam PR. Chętnie przyjmę wszelkie uwagi i komentarze.

**Comment by ArturB** [comment]
@adeele 
"stwierdziłam, że może Wam też się przyda ten kawałek kodu" -> spoko, dzięki :) 
"Chętnie przyjmę wszelkie uwagi i komentarze" -> widzę, że tam są 3 linijki dodane, tak na teraz to zapewne to działa, ale trzeba by przejrzeć, czy nie ma jakichś efektów ubocznych gdzieś. Chętnie to sprawdzę, ale nie wcześniej niż 25 sierpnia, bo do tego czasu mam dużo pracy.

**Comment by pwozniak** [comment]
@Juliette17 Witam,
Sorry za późną odpowiedź, ale aktualnie przebywam na urlopie z ograniczonym dostępem do komputera.


Na razie udało mi się zrobić tylko research i przetestować rozwiązania z SO na szablonie Overleaf. Niestety, nie było żadnego spełniającego nasze wymogi (patrz: niżej).


Jeżeli nie jesteś z EiTI albo twój sekretariat jest liberalny, to polecam ten workaround:
[https://tex.stackexchange.com/a/270484](https://tex.stackexchange.com/a/270484)


@adeele Dzięki za pull request. Jeszcze nie patrzyłem. Jutro będę miał dostęp do komputera, to przetestuję go na Overleaf.


Ale obawiam się, że rozwiązanie nie będzie takie proste. Komendy do appendixów zostały przedefiniowane w pliku CLS. Aktualnie załączniki muszą być numerowane (Załącznik 1. itd.) i znajdować się wyłącznie w spisie załączników.

**Comment by adeele** [comment]
@pwozniak Jeśli chodzi o wygląd załączników to starałam się uzyskać ten sam efekt który był do tej pory, przy czym dodatkowo naprawiłam referencje, aby zachowywały się tak samo jak przy innych elementach (tabelach, rysunkach). Dorzucę zaraz do PR screeny jak to wygląda u mnie, żebyście mogli łatwo ocenić czy jest to zgodne z konwencją.

**Comment by pwozniak** [comment]
@adeele Rzeczywiście. Wszystko się zgadza.

Moja i opinia i uwagi tutaj: #41

**Comment by ArturB** [comment]
W związku z mergem PR https://github.com/ArturB/WUT-Thesis/pull/41, problem jest rozwiązany i temat zamykam.
