### ISSUE TITLE
Oznaczenie źródła skryptu usuwającego pojedyncze litery

### ISSUE THREAD

**Issue by kam193** [ArturB/WUT-Thesis#45]
Skrypt usuwający pojedyncze litery [[link]](https://github.com/ArturB/WUT-Thesis/blob/4a3278d823bc537988163a5a594167bb93c68eb3/eiti/eiti-thesis.cls#L93-L137) pochodzi najwyraźniej z pakietu [impnattypo](https://ctan.org/pkg/impnattypo?lang=en) [(dokumentacja z kodem)](https://sunsite.icm.edu.pl/pub/CTAN/macros/latex/contrib/impnattypo/impnattypo.pdf), ale nie zostało to nigdzie oznaczone. Może warto dorzucić informację o źródle

**Comment by ArturB** [comment]
Skrypt usuwający pojedyncze litery pochodzi ze StackOverflow https://tex.stackexchange.com/questions/27780/one-letter-word-at-the-end-of-line, ale facet ze StackOverflow też może tego sam nie wymyślił. 
Pomyślimy o oznaczeniu tego, albo użyciu wprost tego pakietu w zależnościach.

**Comment by ArturB** [comment]
Z racji, że z w/w wątku na StackOverflow wynika, że ten kawałek kodu zawędrował z SO do impnattypo, a nie na odwrót, temat zamykam.
