### ISSUE TITLE
Warunkowe dodawanie \acronym

### ISSUE THREAD

**Issue by kam193** [ArturB/WUT-Thesis#46]
Makro \acronym jest problematyczne, jeśli ktoś używa innych narzędzie (np. https://www.ctan.org/pkg/acronym). Proponuję opcję konfiguracyjną wyłączającą dodawanie go

**Comment by ArturB** [comment]
No to jest jedna z możliwych instancji problemu typu name confilict i w ogólności może dotyczyć dowolnego makra z szablonu. W LaTeXu nie ma czegoś takiego jak namespace. Żeby całość była spójna, należałoby umożliwić wyłączenie dowolnego makra, albo wszystkim im pododawac prefiksy w nazwach, np. \eitiAcronym. 
Myślę jednak, że to overkill. Jeżeli ktoś koniecznie odczuwa potrzebę użycia niestandardowych pakietów, to należy założyc, że jest też w stanie zajrzeć do [eiti-thesis.cls](https://github.com/ArturB/WUT-Thesis/blob/master/eiti/eiti-thesis.cls) i samodzielnie zmienić sobie nazwę zdefiniowanych tam makr tak, żeby w jego setupie nie było konfliktów. 
W związku z tym raczej nie przewiduję wprowadzenia proponowanej zmiany, niemniej dzięki za zwrócenie uwagi na problem.
