### ISSUE TITLE
\newpage doesn't really starts charpters on the new page

### ISSUE THREAD

**Issue by znfgnu** [ArturB/WUT-Thesis#47]
https://tex.stackexchange.com/a/393798 - `\clearpage` does.

But it also places misplaced object in the centre of the previous page - is it intended behaviour?

**Comment by ArturB** [comment]
Hmm, na styczeń planuję nowy release szablonu i przy tej okazji przemyślę kwestię \newpage vs \clearpage i pozycjonowania obiektów znajdujących się na końcu rozdziału. 
Wątek zostawiam jako task do zrobienia.

**Comment by ArturB** [comment]
Rozwiązane, zamykam.
