### ISSUE TITLE
Using \begin{savenotes} environment for tables results in error

### ISSUE THREAD

**Issue by lapsio** [ArturB/WUT-Thesis#50]
Attempt to use \begin{savenotes} \end{savenotes} environment for table results in compilation error. As result it's not possible to use footnotes inside tables.

(Possible workaround is to use longtables instead. They work with footnotes even without savenotes env)

**Comment by ArturB** [comment]
Szablon juz używa pakietu ```longtables```. Generalnie wygląda to na jakieś interakcje pomiędzy zależnościami szablonu a pakietem ```footnote```, które zapewne dodałeś, żeby mieć dostępne środowisko savenotes. W ogóle temat zależności szablonu trzeba będzie jakoś uporządkować, bo robi się tu już trochę dependency hell. Bedę miał to na uwadze przy najbliższym releasie, tj. około końca stycznia/początku lutego. Wtedy też można się spodziewać rozwiązania problemu przypisów w tabelach.
