### ISSUE TITLE
multiline footnotes are awkwardly misaligned

### ISSUE THREAD

**Issue by lapsio** [ArturB/WUT-Thesis#52]
multiline footnotes are awkwardly misaligned

[img](https://lapsio.bestpony.ml/public/inet/illustrations/susecap1419.png)

**Comment by ArturB** [comment]
Generalnie takie wcięcia są w przypisach od samego początku i ani p. Wiesia ani nikt inny póki co nie zgłaszał co do tego zastrzeżeń... Niemniej może należy pomyśleć o dodaniu jakiejś opcji konfiguracyjnej pozwalającej usunąć/dopasować to wcięcie. 
Do rozważenia.

**Comment by ArturB** [comment]
Rozwiązane, zamykam.
