### ISSUE TITLE
Zmiana loga wydziału + zmiana stylu czcionki bez szeryfów

### ISSUE THREAD

**Issue by aerobird** [ArturB/WUT-Thesis#53]
Cześć. Warto jest uzupełnić o możliwość zmiany loga wydziału, jak również można dodać opcje zmiany paczki na Helvet w celu uzyskania czcionki bez szeryfów. Dodatkowo będę starał się o oficjalne zatwierdzenie tego z logiem wydziału Mechatroniki jako szablon do pracy dyplomowej na tym wydziale.

**Comment by ArturB** [comment]
Niewątpliwie działania idące w kierunku umożliwienia stosowania szablonu na innych wydziałach są ważne, myśleliśmy już trochę o tym, ale jak dotąd nie było za bardzo ani czasu ani okazji. Dzięki za pomysł, a jak uda Ci się coś ustalić na wydziale Mechatro to napisz w komentarzu i będziemy wtedy myśleć co dalej :)

**Comment by ArturB** [comment]
Szablon umożliwia już zmianę loga, czcionki bez szeryfów póki co nie dodajemy, jak będzie zgłaszana potrzeba to do tego wrócimy. Tymczasem zamykam.
