### ISSUE TITLE
LuaTeX + utf8 encoding

### ISSUE THREAD

**Issue by przestaw** [ArturB/WUT-Thesis#55]
Compilation on overleaf with LuaTeX engine yields errors on polish character : ó

`! Undefined control sequence.
ó->\UTFviii@four@octets 
                         ó
l.73 Po skompilowaniu kodu jako biblioteka wspó
                                              łdzielona można skorzystać ...
(That makes 100 errors; please try again.)`

as this exact place occured 100 times changing it to \'o results in error on diffrent polish character

Because disablinf luainpuntenc package results in compilation [without proper polish characters] I expect this to be utf8 related.

Compilation using SCons results in valid document

```
# -*- mode: Python; -*-
import os
import SCons.Builder


# does not work !!!
#VariantDir('../build', './', duplicate=1)

env = Environment(ENV=os.environ)
env.SetDefault(TEXMFHOME=os.path.join(os.environ['HOME'], 'texmf'))

# Use Biber instead of BiBTeX.
env.Replace(BIBTEX='biber')
# Enable SyncTeX.
env.AppendUnique(PDFLATEXFLAGS='-synctex=1')

# Use LuaTeX instead of pdfTeX.
env_lua = env.Clone()
env_lua.Replace(PDFLATEX='lualatex')

pdf = env.PDF(target = 'thesis.pdf', source='main.tex')
pdf_lua = env.PDF(target = 'lua.thesis.pdf', source='main.tex')

prezentacja = env.PDF(target = 'prezentacja.pdf', source='prezentacja.tex')

Depends(pdf, ['bibliografia.bib'])
Depends(pdf_lua, ['bibliografia.bib'])
Depends(prezentacja,['bibliografia.bib'])

env.Clean('.','.sconsign.dblite')
env_lua.Clean('.','.sconsign.dblite')

env.NoClean(pdf)
env_lua.NoClean(pdf_lua)
```

**Comment by ArturB** [comment]
"U mnie działa"
![obraz](https://user-images.githubusercontent.com/11396977/105170742-ad069100-5b1d-11eb-82dd-251c4de42e80.png)
Musisz pokazać większy fragment swojego kodu, żebyśmy mogli dotrzeć do tego, z czego wynika błąd.
