### ISSUE TITLE
Spis rysunków różni się na stronach parzystych i nieparzystych.

### ISSUE THREAD

**Issue by vonHousen** [ArturB/WUT-Thesis#65]
**Opis problemu**
Automatycznie tworzony spis rysunków (generowany na końcu pracy) dodaje pionowe odstępy między kolejnymi pozycjami tylko na co drugiej stronie. 

**Kod źródłowy**
```
\listoffigurestoc     % Spis rysunków     <--- nic nie zmieniane względem templatki
```

**Screenshoty**
![image](https://user-images.githubusercontent.com/42911623/106662162-55970500-65a2-11eb-842c-0fdeac8a5fd7.png)

**Informacje nt. środowiska**
- [x] Overleaf
- [ ] Windows MikTeX
- [ ] Windows TexLive
- [ ] Linux

**Kompilator**
- [x] pdfTeX
- [ ] LuaTeX
- [ ] XeTeX

**Pozostałe**
W mojej pracy mam sporo rysunków i każdy z nich ma opis, czasem na więcej niż jedną linię. Domyślna, automatycznie generowana lista rysunków rozrosła się na dwie strony i wygląda to bardzo nieestetycznie, gdy na jednej z nich pozycje w spisie są rozdzielone pionowym odstępem, a na drugiej nie. 

Sytuację z załączonego drugiego screena łatwo powtórzyć: wystarczy w szablonie Overleafa zduplikować przykładowy rysunek dostatecznie dużą ilość razy, najlepiej z dłuższym opisem.

**Comment by vonHousen** [comment]
Dołączam więcej screenów z szablonu Overleaf'a.
Najwyraźniej problem dotyczy dłuższych podpisów (4 linijki - screen 1. poniżej), bo te 1-2 linijkowe nie sprawiają problemu (screeny 2. i 3. poniżej).

Po zauważeniu tego faktu rozdzieliłem podpis rysunku na 2 części:
```
\caption[Krótki opis zamieszczony w spisie]{Długi opis pod rysunkiem}
```
W ten sposób rozwiązałem swój problem, ale potencjalnie inne osoby mogą być potecjalnie zainteresowane tym bugiem (?). 

![image](https://user-images.githubusercontent.com/42911623/106667655-7c0c6e80-65a9-11eb-9e37-305268b4c624.png)
![image](https://user-images.githubusercontent.com/42911623/106667560-5ed7a000-65a9-11eb-9b58-ec0160c58fc8.png)
![image](https://user-images.githubusercontent.com/42911623/106667609-6c8d2580-65a9-11eb-9cc4-65e9cc234382.png)

**Comment by ArturB** [comment]
Interesujący problem, z pewnością interesujące też będzie znaleźć dla niego rozwiązanie. No na pewno nie jest to zadanie na najbliższe dni/godziny, ale jak znajdę trochę wolnego czasu to pomyślę, co by można z tym zrobić.

**Comment by ArturB** [comment]
Z racji, że takie długie spisy są raczej rzadkie, a znalezienie ogólnego rozwiązania problemu wymagałoby nieproporcjonalnie dużo pracy, to spis rysunków musi zostać jak jest. Dopiszę to do listy znanych problemów na wiki, a ten wątek zamykam.
