### ISSUE TITLE
Domyślne dodanie wsparcia dla podsekcji na poziomach 4 i 5 

### ISSUE THREAD

**Issue by foxale** [ArturB/WUT-Thesis#69]
**Opis proponowanej zmiany**
Podczas pisania pracy niejednokrotnie `\subsubsection` nie wystarcza a my need to go deeper jak Johnny Depp. 
Aby to umożliwić, można skorzystać z komend `\paragraph` oraz `\subparagraph`. Nie są one jednak wtedy numerowane, ani uwzględniane w spisie treści.

Rozwiązanie: 
```
\setcounter{tocdepth}{5}
\setcounter{secnumdepth}{5}
```
**Alternatywy**
Zostawić jak jest.

**Pozostałe**
Nitka z wyjaśnieniem: https://tex.stackexchange.com/questions/186981/is-there-a-subsubsubsection-command

**Comment by foxale** [comment]
Warto również rozważyć opisaną tutaj modyfikację do `\paragraph`: 
https://tex.stackexchange.com/questions/60209/how-to-add-an-extra-level-of-sections-with-headings-below-subsubsection
aby wyglądał i zachowywał się analogicznie do `\subsubsection`

**Comment by ArturB** [comment]
Jutro-pojutrze przejrzę issuesy które się uzbierały i dodam również tę kwestię do kodu szablonu.

**Comment by ArturB** [comment]
Dodane, zamykam.

**Comment by pwozniak** [comment]
Gwoli ścisłości: w zarządzeniu rektora zabrania się 4. i 5. poziomu podpunktów.
