### ISSUE TITLE
Brakujące \vspace po słowniku akronimów

### ISSUE THREAD

**Issue by foxale** [ArturB/WUT-Thesis#70]
**Opis problemu**
Jak w tytule. Sam fakt, że jest spis rysunków, tabel, załączników i słownik akronimów są wciśnięte na jednej stronie jest dziwny, ale ta przerwa wydaje się być zdecydowanie za mała.

**Kod źródłowy**
```
\vspace{0.8cm}
\acronymlist
\acronym{EiTI}{Wydział Elektroniki i Technik Informacyjnych}
\acronym{PW}{Politechnika Warszawska}
\acronym{WEIRD}{ang. \emph{Western, Educated, Industrialized, Rich and Democratic}}

\listoffigurestoc     % Spis rysunków.
\vspace{1cm}          % vertical space
\listoftablestoc      % Spis tabel.
\vspace{1cm}          % vertical space
\listofappendicestoc  % Spis załączników
```

**Screenshoty**
![image](https://user-images.githubusercontent.com/14327763/128612451-dd2a478f-aacd-41fd-94b2-27a4bc10eba6.png)

**Informacje nt. środowiska**
- Overleaf

**Comment by ArturB** [comment]
Są wciśnięte na jednej stronie, żeby szablon dawany Wiesi do akceptacji był bardziej kompaktowy. 

Tutaj \vspace to nie jest jakiś oficjalnie wymagany element szablonu, raczej taki wypełniacz pokazujący, że coś w tym miejscu się pojawi jak wypełnisz swoją pracę treścią. Po prostu dla równomiernego rozmieszczenia nagłówków na stronie. 

Oczywiście w finalnej pracy dyplomowej te spisy zazwyczaj będą na osobnych stronach, ale to już każdy sam może sobie łatwo rozmieścić wedle uznania i raczej nie widzę potrzeby modyfikowania szablonu jako takiego.
