### ISSUE TITLE
Długie opisy pod rysunkami przestają być wycentrowane

### ISSUE THREAD

**Issue by foxale** [ArturB/WUT-Thesis#71]
Czy wielolinijkowy opis (ang. caption) pod rysunkiem powinien być wycentrowany czy nie? 

**Kod źródłowy**
Tutaj wklej fragment kodu LaTeXa, który sprawia problem. 
```
\begin{figure}[!h]
	\label{fig:nowe-logo-pw}
	\centering \includegraphics[width=0.5\linewidth]{logopw2.png}
	\caption{Współczesne logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej }
\end{figure}
```
vs.
```
\begin{figure}[!h]
	\label{fig:nowe-logo-pw}
        \captionsetup{justification=centering}
	\centering \includegraphics[width=0.5\linewidth]{logopw2.png}
	\caption{Współczesne logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej logo Politechniki Warszawskiej }
\end{figure}
```

**Screenshoty**
![image](https://user-images.githubusercontent.com/14327763/128645487-3a8d9e1e-bc8d-4dea-819e-baf7251c6838.png)
vs
![image](https://user-images.githubusercontent.com/14327763/128645515-0c14c9bf-888f-4a2d-a559-086ce5deefd8.png)

**Informacje nt. środowiska**
- Overleaf

**Comment by ArturB** [comment]
Chyba nie było to omawiane z nikim na wydziale, osobiście raczej centrowałbym podpis, w najbliższych dniach przejrzę kwestie, które się uzbierały i dodam to do kodu szablonu.

**Comment by ArturB** [comment]
A tak btw to wersja z Overleafa jest już nieco outdated, ponieważ jej aktualizacja wymaga każdorazowo ręcznej akceptacji przez adminów Overleafa. Ty jesteś sprawnym deweloperem to polecałbym pociągnąć sobie LaTeXa i działać na szablonie bezpośrednio z mastera :)

**Comment by foxale** [comment]
Dobrze wiedzieć, dzięki :)

**Comment by foxale** [comment]
Swoją drogą, może warto trzymać osobnego brancha z aktualnym szablonem Overleafa?

**Comment by Maarrk** [comment]
Według [Zarządzenia Rektora w sprawie ujednolicenia wymogów edytorskich prac dyplomowych](https://www.bip.pw.edu.pl/Wewnetrzne-akty-prawne/Dokumenty-Rektora-PW/Zarzadzenia-Rektora/2016/Zarzadzenie-Rektora-nr-43-2016-z-dnia-8-09-2016) zalecane są podpisy pod rysunkami wyrównane do lewej. Ale z drugiej strony część tamtych propozycji jest według mnie chybiona jak np. font bezszeryfowy.

[zarządzenie w pdf nie skanowane](https://www.wt.pw.edu.pl/content/download/6573/36820/file/43-2016.pdf)

**Comment by ArturB** [comment]
Skoro zarządzenie zaleca podpisy wyrównane do lewej, to zastawiamy jak jest. W sumie może to i lepiej, bo taki długi podpis to jak akapit tekstu, a tekst zawsze piszemy wyrównany do lewej.
