### ISSUE TITLE
UTF-8 is non-searchable and non-copyable

### ISSUE THREAD

**Issue by foxale** [ArturB/WUT-Thesis#73]
**Opis problemu**
... i rozwiązania:
https://t3r1jj.github.io/pl/articles/latex-custom-fonts/

W celu rozwiązania tego tego problemu można skorzystać z innej czcionki - TeX Gyre Termes: `\usepackage{tgtermes}`

**Kod źródłowy**
Dowolne polskie znaki 

**Screenshoty**
Na screenshotach nie widać problemu.

**Informacje nt. środowiska**
- Overleaf

**Comment by ArturB** [comment]
"non-searchable and non-copyable"
U mnie działa :)
![obraz](https://user-images.githubusercontent.com/11396977/131262597-c7c60284-6135-4ebb-9ed2-127e82b4f843.png)

**Comment by foxale** [comment]
Overleaf czy master?

**Comment by ArturB** [comment]
master, jeżeli z podglądu PDF-a na Overleafie nie możesz skopiować tekstu to jest to wina Overleafa, a nie szablonu

**Comment by foxale** [comment]
k'woli ścisłości, nie tylko z podglądu, ale z pobranego pdfa również

**Comment by foxale** [comment]
gwoli ścisłości, nie tylko z podglądu, ale z pobranego pdfa również

**Comment by ArturB** [comment]
A sprawdzałeś, czy zmiana czcionki tak jak w artykule rzeczywiście rozwiązuje problem?

**Comment by foxale** [comment]
Tak, ta zmiana naprawiła moją pracę na Overleafie

**Comment by ArturB** [comment]
Ta czcionka wygląda nieco inaczej niż obecna, jest węższa i cieńsza, moim zdaniem wygląda nieco gorzej, no ale co kto lubi. Ponieważ jednak nikt inny jak dotąd nie zgłaszał tego problemu, to zapewne nie jest to bardzo palący problem, więc nie będziemy już kombinowali przy kroju. Dopiszę może o tym informację gdzieś na wiki, a tymczasem zamykam.

**Comment by foxale** [comment]
To ciekawe, u mnie dodanie tej linijki nie spowodowało żadnej zmiany wizualnej. Sprawdzę jeszcze na czystej wersji Overleafa i mastera, ale to po 16 września :)

**Comment by DjDister** [comment]
stare ale wracam i potwierdzam że błąd występuje nadal - jakby ktoś jeszcze szukał tego błedu to tak jak @foxale wspomniał "\usepackage{tgtermes}" czcionka jest rozwiązaniem - w defaultowym main repo przy kopiowaniu znaków 'ą' oraz 'ę' z pdf'a zamieniane są one na ',e' oraz ',a' dla innych polskich liter działa (np. 'ł' lub 'ó')
