### ISSUE TITLE
Numerowanie równań uwzględniające rozdział

### ISSUE THREAD

**Issue by foxale** [ArturB/WUT-Thesis#74]
**Opis proponowanej zmiany**
Dodać do `eiti-thesis.cls`:
```
%--------------------------------
% Add equation numbering by section
%--------------------------------
\numberwithin{equation}{section}
``` 
Przed:
![image](https://user-images.githubusercontent.com/14327763/130271764-885a44f7-3de1-41a2-9a7d-a2983b1d54e5.png)

Po:
![image](https://user-images.githubusercontent.com/14327763/130271797-5e5f6155-1c12-4ee9-a202-bf3ec7ae8b09.png)

**Alternatywy**
Brak

**Comment by ArturB** [comment]
Dodane, a zatem zamykam.
