### ISSUE TITLE
Tekst wychodzący za margines

### ISSUE THREAD

**Issue by pktiuk** [ArturB/WUT-Thesis#79]
**Opis problemu**
Czasami tekst potrafi wyjść za margines strony.

**Kod źródłowy**

```
\clearpage
\section{Realizacja wielodostępowości}

Architektura wielodostępowa zwana także architekturą wielu dzierżawców (\textit{ang. multi-tenant architecture}) jest jednym z rozwiązań architektonicznych popularnym zwłaszcza w kontekście usług chmurowych oraz rozwiązań SaaS\footnote{Software as a Service}
```

**Screenshoty**
Koniecznie wklej zrzuty ekranu przedstawiające błąd. 
![obraz](https://user-images.githubusercontent.com/45544416/148267644-07291551-c56a-4646-a0cb-8ac030577ef1.png)

**Informacje nt. środowiska**
- [x] Overleaf
- [ ] Windows MikTeX
- [ ] Windows TexLive
- [ ] Linux

**Kompilator**
- [ ] pdfTeX
- [ ] LuaTeX
- [ ] XeTeX

**Pozostałe**
Dodatkowy kontekst i informacje.

**Comment by pwozniak** [comment]
Czysty LaTeX nie potrafi łamać wyrazów z myślnikiem w nazwie.

Na szczęście istnieją biblioteki, które to potrafią:
[https://newbedev.com/how-to-force-latex-not-to-break-the-line-after-a-hyphen](https://newbedev.com/how-to-force-latex-not-to-break-the-line-after-a-hyphen)

**Comment by pktiuk** [comment]
Dzięki za podpowiedź. 

Jeśli sądzicie, że nie warto dodawać tej biblioteki do szablonu to można już zamknąć to Issue.
