### ISSUE TITLE
Wykaz symboli i skrótów powinien być przed spisem rysunków

### ISSUE THREAD

**Issue by pktiuk** [ArturB/WUT-Thesis#80]
**Opis problemu**
Wykaz symboli i skrótów powinien być przed spisem rysunków

Właśnie wysłałem pracę do dziekanatu i otrzymałem tą informację.

**Pozostałe**
Wg zarządzenia rektora nr `57/2017` [link](https://www.elka.pw.edu.pl/Studenci/Kalendarz-ustalenia-plan-zajec/Prace-Dyplomowe)

Układ i kolejność elementów końcowych powinien być taki:

![obraz](https://user-images.githubusercontent.com/45544416/150644019-f7b4870a-575b-4a28-a786-bbfb66835ed3.png)

**Comment by pwozniak** [comment]
Cześć, dzięki za czujność. Pull request poleciał.

**Comment by pktiuk** [comment]
Nie ma sprawy.   
Nawet nie wiecie ile kłopotów nam oszczędziła ta templatka. :D

**Comment by pwozniak** [comment]
@pktiuk Naprawione.
