### ISSUE TITLE
Nowe wymaganie co do prac-Oświadczenie licencyjne

### ISSUE THREAD

**Issue by pktiuk** [ArturB/WUT-Thesis#82]
**Opis proponowanej zmiany**

Na [stronie opisującej składanie pracy dyplomowej](https://www.ii.pw.edu.pl/index.php/ii_pol/Instytut-Informatyki/Nauczanie/Poradnik-dyplomanta/Skladanie-pracy-dyplomowej) w Instytucie Informatyki pojawiło się nowe wymaganie.

Wg rozporządzenia rektora [109 /2021](https://www.bip.pw.edu.pl/Wewnetrzne-akty-prawne/Dokumenty-Rektora-PW/Zarzadzenia-Rektora/2021/Zarzadzenie-nr-109-2021-Rektora-PW-z-dnia-9-11-2021) od teraz w pracy dyplomowej powinno znaleźć się także oświadczenie o udzieleniu licencji.

**Pozostałe**

[licencja.pdf](https://github.com/ArturB/WUT-Thesis/files/7950434/licencja.pdf)

**Comment by pwozniak** [comment]
Cześć, dzięki za informację.

Aktualnie szablon jest zgodny z zarządzeniami 43/2017 i 57/2017 z 2017 roku.

Stopniowo zamierzamy aktualizować szablon do nowych zarządzeń, jeśli czas nam pozwoli.

**Comment by pwozniak** [comment]
@pktiuk Dodałem ten dokument. Dzięki za pomoc.

**Comment by krynju** [comment]
Poza nową karteczą z licencją zmienił się też dotychczasowy załącznik 3
teraz jest on załącznikiem 1: https://www.elka.pw.edu.pl/content/download/30388/198809/file/109_2021_za%C5%82%C4%85cznik%20nr%201.pdf

a ten z licencją to teraz załącznik 3

```
4. Skan wypełnionego i podpisanego załącznika nr 1 do zarządzenia nr 42/2020 Rektora
PW (oświadczenie autora pracy) - uwaga: to oświadczenie powinno znaleźć się także w
pliku pdf, a zatem i wydrukowanej pracy,
5. Skan wypełnionego i podpisanego załącznika nr 3 do zarządzenia nr 42/2020 Rektora
PW (licencja na pracę dyplomową) - uwaga: to oświadczenie powinno znaleźć się
także w pliku pdf, a zatem i wydrukowanej pracy,
```

**Comment by pwozniak** [comment]
Cześć. Ja wstawiłem te, które są na elka.pw.edu.pl, ale zweryfikuję to w wolnej chwili. Dzięki. :)

**Comment by krynju** [comment]
Na stronie II się znowu zmieniły wytyczne, teraz nie ma nic o załącznikach
A najnowsze rozporządzenie w tej sprawie mówi, że *wyłącznie* powinny być one załadowane do USOS APD
Więc szczerze to nie wiem, czy one powinny być w samej pracy według rozporządzenia

https://www.bip.pw.edu.pl/Wewnetrzne-akty-prawne/Dokumenty-Rektora-PW/Zarzadzenia-Rektora/2022/Zarzadzenie-nr-3-2022-Rektora-PW-z-dnia-27-01-2022

**Comment by pwozniak** [comment]
Ok. Usunę to. Dzięki za czujność. Na wszelki wypadek zostawię możliwość dodania tych dokumentów.

**Comment by pwozniak** [comment]
@krynju Gotowe. :)
Ale następnym razem w takiej sytuacji twórz nowe issue i zalinkuj referencję do starego.

Jeszcze raz dzięki za czujność i powodzenia. :)

**Comment by krynju** [comment]
Update dla potomnych: pani Wiesława zaakceptowała pracę bez tych dwóch dokumentów na początku, więc wygląda na to, że rzeczywiście nie są już potrzebne
