### ISSUE TITLE
Możliwość tworzenia wykresów

### ISSUE THREAD

**Issue by Miziol** [ArturB/WUT-Thesis#87]
Czy byłaby możliwość dodania jakiś wykresów? Zarówno do przykładów jak i całego pakietu do szablonu?

I w sumie spis wykresów wtedy też chyba dobrze, gdyby się pojawił ;)

**Comment by ArturB** [comment]
Wykres wstawiasz po prostu jako obrazek, jeżeli oczekujesz dodatkowego spisu z osobnym nagłówkiem, to we własnym zakresie, ręcznie zarządzany spis definiujesz tak, jak wskazano w komentarzu w pliku main.tex - czyli analogicznie, jak spis załączników.

**Comment by pwozniak** [comment]
W rozporządzeniu Rektora ani w LaTeXu nie ma osobnego spisu wykresów. Wykresy w LaTeXu są traktowane jako rysunki i dodawane do spisu rysunków w:
```
\listoffigurestoc
```
Już jeden przykładowy rysunek jest w szablonie (czyli spis rysunków jest w nim widoczny), więc kolejny nie jest potrzebny.
