### ISSUE TITLE
Podwójna numeracja strony

### ISSUE THREAD

**Issue by SzymonKatra** [ArturB/WUT-Thesis#96]
**Opis problemu**
Na niektórych stronach pojawia się numer strony na środku (oprócz tego co jest po lewej/prawej stronie).
Z moich obserwacji wynika, że jest poprawnie tylko na stronach na których zaczyna się nowy rozdział, a na reszcie stron występuje wyżej opisany problem.

**Screenshoty**
Przykład z templatki (problem występuje na stronie 8, 10, 11, 12, 14, 16, na reszcie jest okej):
![image](https://user-images.githubusercontent.com/4078086/153728396-44eb6f71-98d4-435e-a483-3d23be0efcc7.png)
![image](https://user-images.githubusercontent.com/4078086/153728458-9f396d9d-853b-42ce-8980-2c708520ea73.png)

**Informacje nt. środowiska**
- [X] Overleaf
- [ ] Windows MikTeX
- [ ] Windows TexLive
- [ ] Linux

**Kompilator**
- [X] pdfTeX
- [ ] LuaTeX
- [ ] XeTeX

**Comment by ArturB** [comment]
Jest to najwyraźniej błąd regresji między fde8e19418825ca60ca3832f07f5a0c295244ca6 a e6888eb551509aab481703e084edaaec6040cada, ponieważ dla 77ad58a781f5276987df01ae0224cc8d40bf4242 działa dobrze.

**Comment by SzymonKatra** [comment]
@ArturB Dzięki wielkie.
Dodanie `\pagestyle{plain}` za streszczeniem i przed spisem treści naprawia problem.

```
% Streszczenie po polsku dla \langpol
% English abstract if \langeng is set
%-------------------------------------
\cleardoublepage % Zaczynamy od nieparzystej strony
\abstract \lipsum[1-3]
\keywords XXX, XXX, XXX

%----------------------------------------
% Streszczenie po angielsku dla \langpol
% Polish abstract if \langeng is set
%----------------------------------------
\clearpage
\secondabstract \kant[1-3]
\secondkeywords XXX, XXX, XXX

\pagestyle{plain} % <------------ FIX

%--------------
% Spis treści
%--------------
\cleardoublepage % Zaczynamy od nieparzystej strony
\tableofcontents

%------------
% Rozdziały
%------------
```

**Comment by pwozniak** [comment]
Dzięki. Wrzucone. :)
